---

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # amqp
      - "15672:15672"  # http - management
      - "1883:1883"    # mqtt
      - "15692:15692"  # prometheus
      - "25672:25672"  # cluster
      - "15675:15675"  # ws-mqtt
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root123
      # optionally default vhost etc
    command: >
      bash -lc "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt && rabbitmq-server"
    volumes:
      # Bind host directories for data, logs (optional)
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_logs:/var/log/rabbitmq
      # If you want to provide your own config:
      # - ./rabbitmq_conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

